In [167]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import StandardScaler
import joblib

In [169]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()

In [171]:
import pandas as pd
data = pd.read_csv(r"C:\Users\aarna\heart.csv")

In [173]:
data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

Data Mining and Preprocessing

In [176]:
data['ChestPainType'].unique()

array(['ATA', 'NAP', 'ASY', 'TA'], dtype=object)

In [178]:
data['RestingECG'].unique()

array(['Normal', 'ST', 'LVH'], dtype=object)

In [182]:
# Select numerical columns to scale
num_cols = ['Age', 'RestingBP', 'Cholesterol', 'FastingBS', 'MaxHR']

# Initialize and fit scaler on ALL at once
sc = StandardScaler()
data[num_cols] = sc.fit_transform(data[num_cols])

# Save the fitted scaler

In [184]:
data.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,-1.433140,M,ATA,0.410909,0.825070,-0.551341,Normal,1.382928,N,0.0,Up,0
1,-0.478484,F,NAP,1.491752,-0.171961,-0.551341,Normal,0.754157,N,1.0,Flat,1
2,-1.751359,M,ATA,-0.129513,0.770188,-0.551341,ST,-1.525138,N,0.0,Up,0
3,-0.584556,F,ASY,0.302825,0.139040,-0.551341,Normal,-1.132156,Y,1.5,Flat,1
4,0.051881,M,NAP,0.951331,-0.034755,-0.551341,Normal,-0.581981,N,0.0,Up,0

In [186]:
ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')
category = ohe.fit_transform(data[['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope']])
category

,Sex_F,Sex_M,ChestPainType_ASY,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,RestingECG_ST,ExerciseAngina_N,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Flat,ST_Slope_Up
0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
914,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
915,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
916,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
917,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0

In [188]:
category.drop(['Sex_M','ChestPainType_ASY','RestingECG_ST','ExerciseAngina_N','ST_Slope_Flat'],axis=1,inplace=True)

In [190]:
category

,Sex_F,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Up
0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
913,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
914,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
915,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
916,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
917,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [192]:
data = pd.concat([data,category],axis = 1).drop(['Sex','ChestPainType','RestingECG','ExerciseAngina','ST_Slope'],axis = 1)

In [194]:
data.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_F,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Up
0,-1.433140,0.410909,0.825070,-0.551341,1.382928,0.0,0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,-0.478484,1.491752,-0.171961,-0.551341,0.754157,1.0,1,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,-1.751359,-0.129513,0.770188,-0.551341,-1.525138,0.0,0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-0.584556,0.302825,0.139040,-0.551341,-1.132156,1.5,1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.051881,0.951331,-0.034755,-0.551341,-0.581981,0.0,0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [196]:
data_fit = data.drop('HeartDisease',axis=1)
data_fit.head()

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_F,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Up
0,-1.433140,0.410909,0.825070,-0.551341,1.382928,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,-0.478484,1.491752,-0.171961,-0.551341,0.754157,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,-1.751359,-0.129513,0.770188,-0.551341,-1.525138,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-0.584556,0.302825,0.139040,-0.551341,-1.132156,1.5,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
4,0.051881,0.951331,-0.034755,-0.551341,-0.581981,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0

In [198]:
review = StratifiedKFold(n_splits=9)
def get_score(model, x_train , x_test , y_train , y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [200]:
for train_index , test_index in review.split(data_fit,data['HeartDisease']):
    x_train, x_test = data_fit.iloc[train_index], data_fit.iloc[test_index]
    y_train, y_test = data['HeartDisease'].iloc[train_index], data['HeartDisease'].iloc[test_index]
    print(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))

0.8823529411764706
0.9607843137254902
0.8333333333333334
0.9313725490196079
0.7647058823529411
0.8627450980392157
0.8529411764705882
0.7745098039215687
0.803921568627451

In [218]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

# Define parameter grid
param_grid = {
    'n_estimators': [200,300],           # number of trees
    'max_depth': [ 10, 20],           # depth of each tree
    'min_samples_split': [5, 10],           # minimum samples to split a node
    'min_samples_leaf': [2, 4],             # minimum samples at a leaf node
                    # whether to bootstrap samples
}

# Create model
rf = RandomForestClassifier(random_state=42)

# GridSearchCV setup
grid_search = GridSearchCV(estimator=rf,
                           param_grid=param_grid,
                           cv=4,                      # 5-fold CV
                           scoring='accuracy',        # or 'f1', 'roc_auc' etc.
                           n_jobs=-1,                 # use all cores
                           verbose=1)

# Fit the model on training data
grid_search.fit(x_train, y_train)
best_model = grid_search.best_estimator_

Fitting 4 folds for each of 16 candidates, totalling 64 fits

In [219]:
model_score = best_model.score(x_test,y_test)

In [220]:
model_score

0.7549019607843137

In [221]:
model = best_model
model

RandomForestClassifier(max_depth=10, min_samples_leaf=2, min_samples_split=5,
                       n_estimators=300, random_state=42)

In [222]:
# Save model
joblib.dump(model, 'model.pkl')

# Save scaler
joblib.dump(sc, 'scaler.pkl')

# Save encoder
joblib.dump(ohe, 'encoder.pkl')

['encoder.pkl']

In [223]:
import joblib

model = joblib.load('model.pkl')
scaler = joblib.load('scaler.pkl')
encoder = joblib.load('encoder.pkl')

In [224]:
model.predict(x_test)

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0], dtype=int64)

In [225]:
x_test

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,Sex_F,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_LVH,RestingECG_Normal,ExerciseAngina_Y,ST_Slope_Down,ST_Slope_Up
796,0.264027,0.086656,1.922719,-0.551341,0.518368,1.9,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
797,-1.327067,-1.210356,-0.245138,-0.551341,0.832754,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
801,0.264027,-0.021428,-0.135373,-0.551341,-1.250051,2.1,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
804,1.749048,1.491752,0.642129,-0.551341,-0.974963,2.9,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
806,1.749048,0.681120,-0.226844,-0.551341,-0.464087,2.6,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,-0.902775,-1.210356,0.596393,-0.551341,-0.188999,1.2,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
914,1.536902,0.627078,-0.053049,1.813758,0.164684,3.4,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
915,0.370100,-0.129513,-0.620168,-0.551341,-0.857069,1.2,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
916,0.370100,-0.129513,0.340275,-0.551341,1.461525,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
917,-1.645286,0.302825,-0.217696,-0.551341,1.422226,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0